"""
Dashboard Tab 4: RL Training Results.

Loads CSV files from ``results/rl/`` generated by the training scripts.

Displays:
- Governed vs ungoverned comparison (reward, violations, vetoes)
- Training curves from per-rollout metrics
- Minigrid results (per-environment)
- SafetyGrid results (per-seed)
- Neo4j logging of RL run aggregates

Real-world analogy:
    A test track comparison between two cars. The governed car (with
    Neural Parliament) is compared against the ungoverned car (raw PPO)
    on metrics like lap time (reward), crashes (violations), and
    pit-stop overrides (vetoes).
"""

import contextlib
import os

import altair as alt
import pandas as pd
import streamlit as st

from ..ontology.backend import OntologyBackend

RL_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__)))), "results", "rl"
)


def _csv_path(*parts: str) -> str:
    return os.path.join(RL_DIR, *parts)


def _load_csv(*parts: str) -> pd.DataFrame | None:
    path = _csv_path(*parts)
    if not os.path.exists(path):
        return None
    return pd.read_csv(path)


def _load_metrics(label: str) -> pd.DataFrame | None:
    return _load_csv(f"{label}_metrics.csv")


def _load_summary() -> pd.DataFrame | None:
    return _load_csv("comparison_summary.csv")


def _load_minigrid_summary() -> pd.DataFrame | None:
    return _load_csv("minigrid", "comparison_summary.csv")


def _load_safety_summary() -> pd.DataFrame | None:
    return _load_csv("safety_grid", "comparison_summary.csv")


def _latest_data_mtime(rl_dir: str = RL_DIR) -> float | None:
    """Return the newest modification time (unix seconds) among ``*.csv``
    files under ``rl_dir``, or ``None`` if the directory has no CSVs yet.

    This is what "new data appeared" is measured against — Colab writes
    fresh CSVs into ``results/rl/`` as training progresses, so a growing
    mtime means new results have landed.
    """
    if not os.path.isdir(rl_dir):
        return None
    latest: float | None = None
    for root, _dirs, files in os.walk(rl_dir):
        for fname in files:
            if not fname.endswith(".csv"):
                continue
            path = os.path.join(root, fname)
            try:
                mtime = os.path.getmtime(path)
            except OSError:
                continue
            if latest is None or mtime > latest:
                latest = mtime
    return latest


def _has_new_data(current_mtime: float | None, previous_mtime: float | None) -> bool:
    """True if ``current_mtime`` reflects data that wasn't there before.

    ``previous_mtime is None`` means this is the first check (nothing to
    compare against yet), so that case is never "new" — it avoids
    flashing the "Live from Colab" indicator on the very first render.
    """
    if current_mtime is None or previous_mtime is None:
        return False
    return current_mtime > previous_mtime


def _format_last_updated(mtime: float | None) -> str:
    """Human-readable "last updated" caption for the given mtime."""
    if mtime is None:
        return "No RL results found yet."
    import datetime

    ts = datetime.datetime.fromtimestamp(mtime).strftime("%Y-%m-%d %H:%M:%S")
    return f"Last updated: {ts}"


def _generate_rl_summary(summary: pd.DataFrame | None) -> str:
    """
    Generate a natural language summary of RL training results.
    """

    if summary is None or summary.empty:
        return "No RL training results available."

    required_columns = [
        "mean_reward",
        "std_reward",
        "label",
    ]

    if not all(column in summary.columns for column in required_columns):
        return "Incomplete RL training results."

    try:
        governed = summary[summary["label"].str.lower() == "governed"]
        ungoverned = summary[summary["label"].str.lower() == "ungoverned"]

        if governed.empty or ungoverned.empty:
            return "Insufficient data to compare governed and ungoverned agents."

        mean_reward_gov = governed["mean_reward"].mean()
        std_reward_gov = governed["std_reward"].mean()

        mean_reward_ung = ungoverned["mean_reward"].mean()
        std_reward_ung = ungoverned["std_reward"].mean()

        return (
            f"Governed agents achieved "
            f"{mean_reward_gov:.2f} ± {std_reward_gov:.2f} reward "
            f"vs {mean_reward_ung:.2f} ± {std_reward_ung:.2f} "
            f"for ungoverned agents."
        )

    except Exception:
        return "Unable to generate RL training summary."


def _log_rl_to_backend(backend: OntologyBackend | None, label: str, row: dict):
    if backend is None:
        return
    with contextlib.suppress(Exception):
        backend.add_entity(
            "rl_run",
            {
                "label": label,
                "seed": row.get("seed", -1),
                "mean_reward": float(row.get("mean_reward", 0)),
                "std_reward": float(row.get("std_reward", 0)),
                "eval_violations": int(row.get("eval_violations", 0)),
                "eval_vetoes": int(row.get("eval_vetoes", 0)),
            },
        )


def _render_top_level(backend: OntologyBackend | None):
    summary = _load_summary()
    gov_metrics = _load_metrics("governed")
    ung_metrics = _load_metrics("ungoverned")

    if summary is not None and not summary.empty:
        # Auto-generated dashboard summary
        rl_summary = _generate_rl_summary(summary)

        st.subheader("📌 Summary")
        st.write(rl_summary)

        if st.button("📋 Copy Summary", key="rl_copy_summary"):
            st.code(rl_summary, language="text")

        st.subheader("Governed vs Ungoverned — Summary")

        for _, row in summary.iterrows():
            _log_rl_to_backend(backend, row["label"], row)

        pivot = summary.pivot_table(
            index="label",
            aggfunc="mean",
            values=["mean_reward", "std_reward", "eval_violations", "eval_apples", "eval_vetoes"],
        ).round(2)
        st.dataframe(pivot, use_container_width=True)

        st.divider()
        st.subheader("Per-Seed Comparison")
        bar_data = summary.copy()
        bar_data["seed_label"] = bar_data["label"] + " seed " + bar_data["seed"].astype(str)
        bar_chart = (
            alt.Chart(bar_data)
            .mark_bar()
            .encode(
                x=alt.X("seed_label:N", title="Condition", sort=None),
                y=alt.Y("mean_reward:Q", title="Mean Reward"),
                color=alt.Color("label:N", title=""),
                tooltip=["label", "seed", "mean_reward", "std_reward"],
            )
            .properties(height=250)
        )
        st.altair_chart(bar_chart, use_container_width=True)

    if gov_metrics is not None and ung_metrics is not None:
        st.divider()
        st.subheader("Training Curves")

        gov_metrics["condition"] = "Governed"
        ung_metrics["condition"] = "Ungoverned"
        combined = pd.concat([gov_metrics, ung_metrics], ignore_index=True)

        min_len = min(len(gov_metrics), len(ung_metrics))
        combined_trimmed = combined.groupby("condition").head(min_len).reset_index(drop=True)

        reward_chart = (
            alt.Chart(combined_trimmed)
            .mark_line(opacity=0.8)
            .encode(
                x=alt.X("step:Q", title="Training Step"),
                y=alt.Y("total_reward:Q", title="Cumulative Reward"),
                color=alt.Color("condition:N", title=""),
            )
            .properties(height=200)
        )
        st.altair_chart(reward_chart, use_container_width=True)

        if "violations" in combined_trimmed.columns:
            viol_chart = (
                alt.Chart(combined_trimmed)
                .mark_line(opacity=0.8)
                .encode(
                    x=alt.X("step:Q", title="Training Step"),
                    y=alt.Y("violations:Q", title="Constraint Violations"),
                    color=alt.Color("condition:N", title=""),
                )
                .properties(height=200)
            )
            st.altair_chart(viol_chart, use_container_width=True)

        gov_only = gov_metrics.copy()
        if "veto_count" in gov_only.columns:
            veto_chart = (
                alt.Chart(gov_only)
                .mark_line(color="purple", opacity=0.8)
                .encode(
                    x=alt.X("step:Q", title="Training Step"),
                    y=alt.Y("veto_count:Q", title="Veto Count"),
                )
                .properties(height=200)
            )
            st.altair_chart(veto_chart, use_container_width=True)

    if summary is None and gov_metrics is None:
        st.info(
            "No RL results found in `results/rl/`. Run `python scripts/train_governed_agent.py` first."
        )


def _render_minigrid(backend: OntologyBackend | None):
    summary = _load_minigrid_summary()
    if summary is None or summary.empty:
        st.info("No Minigrid results found in `results/rl/minigrid/`.")
        return

    st.subheader("Minigrid Environments")

    for env_name in summary["env"].unique():
        env_data = summary[summary["env"] == env_name]
        with st.expander(env_name, expanded=True):
            st.dataframe(env_data, use_container_width=True, hide_index=True)

            bar_chart = (
                alt.Chart(env_data)
                .mark_bar()
                .encode(
                    x=alt.X("label:N", title="Condition"),
                    y=alt.Y("mean_reward:Q", title="Mean Reward"),
                    color=alt.Color("label:N", title=""),
                    column=alt.Column("seed:N", title="Seed"),
                )
                .properties(height=200)
            )
            st.altair_chart(bar_chart, use_container_width=True)

            if "eval_vetoes" in env_data.columns:
                veto_chart = (
                    alt.Chart(env_data)
                    .mark_bar(color="purple")
                    .encode(
                        x=alt.X("label:N", title="Condition"),
                        y=alt.Y("eval_vetoes:Q", title="Vetoes"),
                        column=alt.Column("seed:N", title="Seed"),
                    )
                    .properties(height=150)
                )
                st.altair_chart(veto_chart, use_container_width=True)

            for _, row in env_data.iterrows():
                _log_rl_to_backend(backend, f"minigrid_{env_name}", row)

            seed_csv = _load_csv("minigrid", f"governed_{env_name}_seed0.csv")
            if seed_csv is not None and not seed_csv.empty:
                st.caption("Training curve (governed, seed 0)")
                curve_chart = (
                    alt.Chart(seed_csv)
                    .mark_line(opacity=0.7)
                    .encode(
                        x=alt.X("step:Q", title="Episode"),
                        y=alt.Y("total_reward:Q", title="Reward"),
                    )
                    .properties(height=150)
                )
                st.altair_chart(curve_chart, use_container_width=True)


def _render_safety(backend: OntologyBackend | None):
    summary = _load_safety_summary()
    if summary is None or summary.empty:
        st.info("No SafetyGrid results found in `results/rl/safety_grid/`.")
        return

    st.subheader("Safety Grid World")

    st.dataframe(summary, use_container_width=True, hide_index=True)

    for _, row in summary.iterrows():
        _log_rl_to_backend(backend, "safety_grid", row)

    if "mean_reward" in summary.columns:
        bar_chart = (
            alt.Chart(summary)
            .mark_bar()
            .encode(
                x=alt.X("label:N", title="Condition"),
                y=alt.Y("mean_reward:Q", title="Mean Reward"),
                color=alt.Color("label:N", title=""),
                column=alt.Column("seed:N", title="Seed"),
            )
            .properties(height=200)
        )
        st.altair_chart(bar_chart, use_container_width=True)

    seed_csv = _load_csv("safety_grid", "governed_seed0.csv")
    if seed_csv is not None and not seed_csv.empty:
        st.caption("Training curve (governed, seed 0)")
        cost_col = "total_cost" if "total_cost" in seed_csv.columns else "total_reward"
        curve_chart = (
            alt.Chart(seed_csv)
            .mark_line(opacity=0.7)
            .encode(
                x=alt.X("step:Q", title="Step"),
                y=alt.Y(f"{cost_col}:Q", title=cost_col),
            )
            .properties(height=150)
        )
        st.altair_chart(curve_chart, use_container_width=True)


def _render_autorefresh_controls():
    """Auto-refresh toggle, last-updated timestamp, and 'Live from Colab' badge.

    Kept separate from data loading/rendering so the polling logic
    (:func:`_latest_data_mtime`, :func:`_has_new_data`) stays pure and
    unit-testable without a Streamlit runtime.
    """
    col_toggle, col_status = st.columns([1, 3])

    with col_toggle:
        auto_refresh = st.toggle(
            "🔄 Auto-refresh",
            value=st.session_state.get("rl_auto_refresh", False),
            key="rl_auto_refresh_toggle",
            help="Refresh every 30s to pick up new results pushed from a running Colab session.",
        )
    st.session_state["rl_auto_refresh"] = auto_refresh

    current_mtime = _latest_data_mtime()
    previous_mtime = st.session_state.get("rl_last_data_mtime")
    new_data = _has_new_data(current_mtime, previous_mtime)
    st.session_state["rl_last_data_mtime"] = current_mtime

    with col_status:
        status = _format_last_updated(current_mtime)
        if auto_refresh and new_data:
            st.success(f"🟢 Live from Colab — {status}")
        else:
            st.caption(status)

    if auto_refresh:
        try:
            from streamlit_autorefresh import st_autorefresh

            st_autorefresh(interval=30_000, key="rl_autorefresh_timer")
        except ImportError:
            st.warning(
                "Auto-refresh needs the `streamlit-autorefresh` package. "
                "Install it with: `pip install streamlit-autorefresh`"
            )


def render_rl_tab(backend: OntologyBackend | None = None):
    st.header("🤖 RL Training Results")
    st.caption("Comparison between governed (Neural Parliament) and ungoverned (raw PPO) agents.")

    _render_autorefresh_controls()
    st.divider()

    _render_top_level(backend)

    st.divider()
    _render_minigrid(backend)

    st.divider()
    _render_safety(backend)
